# Site settings
title: Alex P. Grover
tag_text: Alex P. Grover
description: Alex P. Grover is a NYC-based composer.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
